---
- name: Create database on influxdb
  command: influx -execute 'CREATE DATABASE {{ influxdb_database_name }}'
  register: _create_database
  until: _create_database is succeeded
  retries: 3
  delay: 2
  changed_when: false
