# - block:
#     - name: Import InfluxDB GPG signing key
#       get_url:
#         url: 'https://repos.influxdata.com/influxdata-archive_compat.key'
#         dest: /etc/apt/keyrings/influxdata-archive_compat.asc
#         mode: 0644
#         force: true
#       tags:
#         - influxdb

#     - name: Add InfluxDB repository
#       apt_repository:
#         repo: 'deb [signed-by=/etc/apt/keyrings/influxdata-archive_compat.asc] https://repos.influxdata.com/debian stable main'
#         state: present
#         update_cache: false
#       tags:
#         - influxdb

- name: Install InfluxDB using Ubuntu repository
  apt:
    name:
      - influxdb
      - influxdb-client
    state: "{{ (influxdb_version == 'latest') | ternary('latest', 'present') }}"

- name: unmask influxdb
  systemd:
    masked: no
    daemon_reload: yes
    enabled: yes
    name: influxdb
  notify: restart influxdb
