- block:
    - name: Install dependencies
      apt:
        name: "{{ grafana_dependencies }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2

- block:
    - name: Import Grafana GPG signing key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present
        validate_certs: yes
      register: _add_apt_key
      until: _add_apt_key is succeeded
      retries: 5
      delay: 2

    - name: Add Grafana repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
        update_cache: yes
      register: _update_apt_cache
      until: _update_apt_cache is succeeded
      retries: 5
      delay: 2

- name: Install Grafana
  apt:
    name:
      - grafana
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
    update_cache: yes
  notify: restart grafana-server
