# - block:
#     - name: Import Grafana GPG signing key
#       get_url:
#         url: ' https://apt.grafana.com/gpg.key'
#         dest: /etc/apt/keyrings/grafana.asc
#         mode: 0644
#         force: true
#       tags:
#         - grafana

#     - name: Add Grafana repository
#       apt_repository:
#         repo: 'deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main'
#         state: present
#         update_cache: false
#       tags:
#         - grafana

- block:
    - name: Install dependencies
      apt:
        name:
          - gnupg2
          - curl
          - software-properties-common
          - apt-transport-https
        state: present

- name: Install Grafana using Ubuntu repository
  apt:
    name:
      - grafana
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  notify: restart grafana-server
