---
- name: Install Python3
  apt:
    name:
      - python3-dev
      - python3-pip
    state: present
  tags:
    - install_python3

- name: Install Python libraries
  pip:
    name:
      - bluepy
      - pandas
      - prometheus-client
  tags:
    - install_python3

- name: Install libraries
  apt:
    name:
      - libglib2.0-dev
      - bluez
      - libatlas-base-dev
    state: present
  tags:
    - install_libraries
