---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: hostname_setup

- name: Replace hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    backrefs: yes
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1  {{ inventory_hostname }}'
  tags: hostname_setup
